app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.secret_key = 'a1b2c3d4e5f6g7h8i9j0'
    app.config['IMAGE_EXTS'] = [".png", ".jpg", ".heic"]
    from .routes import main
    app.register_blueprint(main)

    return app

app/routes.py
"""
This module contains the routes for the Flask application.

Attributes:
    main (Blueprint): The main Blueprint for the Flask application.
"""
from threading import Thread
from pathlib import Path
import binascii
import os
import pickle
from flask import Blueprint, render_template, current_app, send_from_directory,flash,redirect,url_for, request, jsonify
import faiss
import numpy as np
import torch
from transformers import AutoImageProcessor, AutoModel
from PIL import Image
from werkzeug.utils import secure_filename
from pillow_heif import register_heif_opener

register_heif_opener()
main = Blueprint('main', __name__)

device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
model = AutoModel.from_pretrained('facebook/dinov2-small').to(device)
model.eval()


@main.route('/')
def index():
    """
    Renders the index.html template.

    Returns:
        The rendered index.html template.
    """
    return render_template('index.html')

@main.route('/setup')
def setup():
    # Logic for Google account setup
    return render_template('setup.html')

@main.route('/sync')
def sync():
    # Logic for syncing latest images
    return render_template('sync.html')

def add_vector_to_index(embedding, index):
    #convert embedding to numpy
    vector = embedding.detach().cpu().numpy()
    #Convert to float32 numpy
    vector = np.float32(vector)
    #Normalize vector: important to avoid wrong results when searching
    faiss.normalize_L2(vector)
    #Add to index
    index.add(vector)


@main.route('/update_index')
def update_index():
    # Path to your images and index
    images_path = './gallery/photos/'
    index_path = 'vector.index'
    pickle_path = 'images.pkl'
    print('Syncing images from {} to index {}'.format(images_path, index_path))
    # Check if index and pickle files exist
    if os.path.exists(index_path) and os.path.exists(pickle_path):
        with open(pickle_path, 'rb') as f:
            images = pickle.load(f)
        index = faiss.read_index(index_path)
    else:
        images = []
        index = faiss.IndexFlatL2(384)  # Adjust dimensions as needed

    # Process images and update the index
    process_images_and_update_index(images, images_path, index)

    # display success message
    flash('Sync successful. Total images indexed: {}'.format(index.ntotal))
    return redirect(url_for('main.sync'))


def process_images_and_update_index(images, images_path, index):
    current_images = set()
    deleted_ids=[]
    for root, _, files in os.walk(images_path):
        for file in files:
            if file.endswith(('.jpg', '.png', '.heic')):
                image_path = os.path.join(root, file)
                current_images.add(image_path)
                if image_path not in images:
                    img = Image.open(image_path).convert('RGB')
                    with torch.no_grad():
                        inputs = processor(images=img, return_tensors="pt").to(device)
                        outputs = model(**inputs)
                    features = outputs.last_hidden_state.mean(dim=1)
                    add_vector_to_index(features, index)
                    print('Added image {} to index'.format(image_path))
                    # add image to images list
                    images.append(image_path)
    deleted_images = set(images) - current_images

    if deleted_images:
        deleted_ids = [images.index(image) for image in deleted_images]
        print('Deleting {} images from index'.format(len(deleted_ids)))
        index.remove_ids(np.array(deleted_ids))

    images[:] = [image for image in images if image not in deleted_images]
    # Check if the number of images in the index matches the number of images
    assert len(images) == index.ntotal
    # Save the updated index and image list
    faiss.write_index(index, 'vector.index')
    with open('images.pkl', 'wb') as f:
        pickle.dump(images, f)
    print('Index updated successfully')

def encode(filepath):
    """
    Encodes the given filepath into a hexadecimal string.

    Args:
        filepath (str): The path of the file to be encoded.

    Returns:
        str: The hexadecimal representation of the filepath.
    """
    return binascii.hexlify(filepath.encode('utf-8')).decode()

@main.route('/cdn/<path:filepath>')
def download_file(filepath):
    """
    Download a file from the specified filepath.

    Args:
        filepath (str): The path of the file to be downloaded.

    Returns:
        str: The file content if found, or "File not found" with status code 404.
    """
    filepath_decoded = binascii.unhexlify(filepath.encode('utf-8')).decode()
    # gallery_root = Path(__file__).resolve().parent.parent / 'gallery'
    file_path = Path.cwd() / 'gallery' / filepath_decoded
    print(file_path)
    if not file_path.is_file():
        return "File not found", 404
    return send_from_directory(str(file_path.parent), file_path.name, as_attachment=False)

@main.route('/cdn2/<path:filepath>')
def download_file2(filepath):
    """
    Download a file from the specified filepath.

    Args:
        filepath (str): The path of the file to be downloaded.

    Returns:
        str: The file content if found, or "File not found" with status code 404.
    """
    filepath_decoded = binascii.unhexlify(filepath.encode('utf-8')).decode()
    # gallery_root = Path(__file__).resolve().parent.parent / 'gallery'
    file_path = Path.cwd() / filepath_decoded
    print(file_path)
    if not file_path.is_file():
        return "File not found", 404
    return send_from_directory(str(file_path.parent), file_path.name, as_attachment=False)

@main.route('/gallery')
def gallery():
    """
    Renders the gallery page with a list of image paths.

    Returns:
        A rendered HTML template with the image paths.
    """
    root_dir = Path(__file__).resolve().parent.parent / 'gallery'
    image_paths = []
    for path in root_dir.glob('**/*'):  # Using glob instead of rglob if you want non-recursive
        if path.is_file() and path.suffix.lower() in [ext.lower() for ext in current_app.config['IMAGE_EXTS']]:
            rel_path = path.relative_to(root_dir)
            image_paths.append(encode(str(rel_path)))
    return render_template('gallery.html', paths=image_paths)

@main.route('/search')
def search():
    return render_template('search.html')


def perform_search(image_path, num_results):

    index = faiss.read_index('vector.index')
    image_list = pickle.load(open('images.pkl', 'rb'))

    # Load the model and processor
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
    model = AutoModel.from_pretrained('facebook/dinov2-small').to(device)
    model.eval()

    # Load and process the image
    image = Image.open(image_path).convert('RGB')
    inputs = processor(images=image, return_tensors="pt").to(device)

    # Extract features
    with torch.no_grad():
        outputs = model(**inputs)
    
    # Normalize the features
    embeddings = outputs.last_hidden_state.mean(dim=1)
    vector = embeddings.detach().cpu().numpy()
    vector = np.float32(vector)
    faiss.normalize_L2(vector)

    # Read the index and perform the search
    
    distances, indices = index.search(vector, num_results)
    encoded_paths = [encode(image_list[idx]) for idx in indices[0]]
    distances = distances[0].tolist()
    
    return list(zip(encoded_paths, distances))

@main.route('/perform_search', methods=['POST'])
def search_route():
    # Check if the index files exist
    if not os.path.exists('vector.index') or not os.path.exists('images.pkl'):
        flash('Please sync your images before searching.')
        return redirect(url_for('main.index'))

    # Process the uploaded image
    image_file = request.files['image']
    num_results = request.form.get('num_results', 3, type=int)
    if image_file:
        filename = secure_filename(image_file.filename)
        image_path = os.path.join('query_images', filename)
        #create query_images folder if it does not exist
        if not os.path.exists('query_images'):
            os.makedirs('query_images')
        image_file.save(image_path)

        # Perform the search
        search_results = perform_search(image_path, num_results)
        print(search_results)
        return render_template('results.html', search_results=search_results)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Seeker - CBIR System</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Image Seeker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/setup">Setup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/sync">Sync</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/gallery">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/search">Search</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        <!-- Content will be rendered here -->
        {% endblock %}
    </div>

    <!-- Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/gallery.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
</head>
<body>
    {% extends "base.html" %}

    {% block content %}
    <div class="container mt-4">
        <h1 class="text-center">Image Gallery</h1>
        <div class="row">
            {% for path in paths %}
            <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                <img src="{{ url_for('main.download_file', filepath=path) }}" class="img-thumbnail img-fluid" onclick="showImageModal(this.src)" style="object-fit: cover; height: 200px; width: 100%;" alt="Gallery Image">
            </div>
            {% endfor %}
        </div>
    </div>
    
    <!-- Image Modal -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="imageModalLabel">Image Preview</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="" id="modalImage" class="img-fluid" alt="Responsive Image">
                </div>
            </div>
        </div>
    </div>
    
    <script>
        function showImageModal(src) {
            var modalImage = document.getElementById('modalImage');
            modalImage.src = src;
            var imageModal = new bootstrap.Modal(document.getElementById('imageModal'));
            imageModal.show();
        }
    </script>
    {% endblock %}
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Seeker - CBIR System</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <div class="container-fluid vh-100 d-flex flex-column justify-content-center align-items-center text-center">
        <h1 class="mb-2">Welcome to Image Seeker</h1>
        <p class="mb-4">Discover images easily with our advanced CBIR system.</p>
        <p>Connecting content through visual similarity.</p>
        
        <div class="button-group mt-4">
            <a href="/setup" class="btn btn-info m-2">Setup</a>
            <a href="/sync" class="btn btn-warning m-2">Sync</a>
            <a href="/gallery" class="btn btn-primary m-2">Gallery</a>
            <a href="/search" class="btn btn-success m-2">Search</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/results.html
<!DOCTYPE html>
<html>
<body>
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center">Search Results</h1>
    <div class="row">
        {% for path, distance in search_results %}
        <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
            <img src="{{ url_for('main.download_file2', filepath=path) }}" class="img-thumbnail img-fluid" onclick="showImageModal(this.src)" style="object-fit: cover; height: 200px; width: 100%;" alt="Search Result">
            <p>Distance: {{ distance }}</p>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Image Modal -->
<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="imageModalLabel">Image Preview</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img src="" id="modalImage" class="img-fluid" alt="Responsive Image">
            </div>
        </div>
    </div>
</div>

<script>
    function showImageModal(src) {
        var modalImage = document.getElementById('modalImage');
        modalImage.src = src;
        var imageModal = new bootstrap.Modal(document.getElementById('imageModal'));
        imageModal.show();
    }
</script>
{% endblock %}
</body>
</html>

app/templates/search.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center">Image Search</h1>
    <form id="searchForm" method="post" enctype="multipart/form-data" action="/perform_search">
        <input type="file" name="image" accept=".jpg, .jpeg, .png, .heic" required>
        <input type="number" name="num_results" placeholder="Number of images to retrieve" min="1" value="3">
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
{% endblock %}

app/templates/setup.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center">Application Setup</h1>
    <p>Before you run gphotos_sync for the first time, you need to create your own OAuth client ID. Follow these instructions: <a target="_blank" href="https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html#client-id">Creating an OAuth Client ID</a>.</p>
    <p>Once the client ID is created, download it as <code>client_secret.json</code> and save it under the application configuration directory:</p>
    <ul>
        <li>~/Library/Application Support/gphotos-sync/ (Mac OS X)</li>
        <li>~/.config/gphotos-sync/ (Linux)</li>
        <li>C:\Users\&lt;username&gt;\AppData\Local\gphotos-sync\gphotos-sync\ (Windows)</li>
    </ul>
    <p>After setting up the client ID, you are ready to run gphotos-sync. The first run will require a user login. See <a href="https://gilesknap.github.io/gphotos-sync/main/tutorials/login.html#login" target="_blank">User Login OAuth Flow</a>.</p>
    <h2 class="mt-4">Syncing Google Photos</h2>
    <p>To sync your Google Photos with the application, follow these steps:</p>
    <ol>
        <li>Open your command line interface (Terminal, Command Prompt, etc.).</li>
        <li>Navigate to the root directory of the application.</li>
        <li>Run the command <code>gphotos-sync .\gallery\</code> to start the synchronization process.</li>
        <li>Follow any prompts in the command line to complete the sync.</li>
    </ol>
    <p>This will sync your Google Photos to the 'gallery' folder in the application directory.</p>
    <!-- 
    <button id="runSyncBtn" class="btn btn-success">Run gphotos-sync</button> -->
</div>

<!-- <script>

document.getElementById('runSyncBtn').onclick = function() {
    // Implement JavaScript to run `gphotos-sync` and handle the output
};
</script> -->
{% endblock %}

app/templates/sync.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Update Vector Index</h2>
    <p>Click the button below to update the vector index with the latest images from the gallery.</p>
    <button id="updateIndexBtn" class="btn btn-primary">Update Index</button>

    <!-- Include JavaScript to handle the button click -->
    <script>
        document.getElementById('updateIndexBtn').onclick = async function() {
            const response = await fetch('/update_index');
            const data = await response.json();
            alert(data.message);
        };
    </script>
</div>
{% endblock %}